Repository vapor/postgres-nio, pull requests merged in 2019-12, with the labels that each got.

#62 fix ci w/ v1
  .github/workflows/test.yml
Labels: bug

#63 add data type to bind
  Sources/PostgresNIO/Connection/PostgresClient+Query.swift
  Sources/PostgresNIO/Data/PostgresData+String.swift
  Sources/PostgresNIO/Data/PostgresData+UUID.swift
  Sources/PostgresNIO/Message/PostgresMessage+Parse.swift
  Tests/PostgresNIOTests/NIOPostgresTests.swift
  Tests/PostgresNIOTests/XCTestManifests.swift
Labels: enhancement

#64 beta.2
  .github/workflows/test.yml
  Tests/LinuxMain.swift
  Tests/PostgresNIOTests/XCTestManifests.swift
Labels: enhancement

#65 array of double fixes
  Sources/PostgresNIO/Data/PostgresData+Double.swift
  Sources/PostgresNIO/Data/PostgresData.swift
  Sources/PostgresNIO/Utilities/NIOUtils.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
Labels: bug

#60 Add support for receiving and dispatching NotificationResponse messages
  Sources/PostgresNIO/Connection/PostgresClient+Query.swift
  Sources/PostgresNIO/Connection/PostgresClient+SimpleQuery.swift
  Sources/PostgresNIO/Connection/PostgresConnection+Connect.swift
  Sources/PostgresNIO/Connection/PostgresConnection+Notifications.swift
  Sources/PostgresNIO/Connection/PostgresRequest.swift
  Sources/PostgresNIO/Message/PostgresMessage+NotificationResponse.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
Labels: enhancement

#66 add untyped array methods to PostgresData
  .github/workflows/test.yml
  Sources/PostgresNIO/Data/PostgresData+Array.swift
  Sources/PostgresNIO/Data/PostgresData+JSONB.swift
  Sources/PostgresNIO/Data/PostgresData.swift
Labels: enhancement

#68 add byte to message verifier test
  Package.swift
  Sources/PostgresNIO/Message/PostgresMessage+0.swift
  Sources/PostgresNIO/Message/PostgresMessage+Authentication.swift
  Sources/PostgresNIO/Message/PostgresMessageDecoder.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
Labels: enhancement

#70 publicize row properties
  Sources/PostgresNIO/Data/PostgresRow.swift
Labels: enhancement

#73 Remove BPCHAR to Swift Integer conversion
  Sources/PostgresNIO/Data/PostgresData+Int.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
Labels: bug, semver-patch
