Repository vapor/postgres-nio, pull requests merged in 2020-03, with the labels that each got.

#86 Send terminate message on close
  Sources/PostgresNIO/Connection/PostgresConnection+Connect.swift
  Sources/PostgresNIO/Connection/PostgresConnection+Database.swift
  Sources/PostgresNIO/Connection/PostgresConnection.swift
  Sources/PostgresNIO/Message/PostgresMessage+BackendKeyData.swift
  Sources/PostgresNIO/Message/PostgresMessage+Terminate.swift
  Sources/PostgresNIO/Message/PostgresMessageDecoder.swift
  Sources/PostgresNIO/Message/PostgresMessageEncoder.swift
  Sources/PostgresNIO/PostgresDatabase+Query.swift
  Sources/PostgresNIO/PostgresDatabase+SimpleQuery.swift
  Sources/PostgresNIO/PostgresDatabase.swift
  Sources/PostgresNIO/PostgresRequest.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
  Tests/PostgresNIOTests/Utilities.swift
Labels: bug, semver-patch

#88 Update to Metrics 2.0
  Package.swift
Labels: enhancement, semver-minor

#91 Give the tests a bit of a sprucing up
  Tests/PostgresNIOTests/PerformanceTests.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
  Tests/PostgresNIOTests/Utilities.swift
Labels: enhancement
