Repository vapor/postgres-nio, pull requests merged in 2020-04, with the labels that each got.

#95 Add query metadata
  Sources/PostgresNIO/Message/PostgresMessage+CommandComplete.swift
  Sources/PostgresNIO/PostgresDatabase+Query.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
Labels: enhancement, semver-major

#15 Prepared Statement API
  Sources/PostgresNIO/Connection/PostgresConnection+Database.swift
  Sources/PostgresNIO/Connection/PostgresDatabase+Close.swift
  Sources/PostgresNIO/Connection/PostgresDatabase+PreparedQuery.swift
  Sources/PostgresNIO/Message/PostgresMessage+Close.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
Labels: enhancement

#96 copy data row column slice
  Sources/PostgresNIO/Message/PostgresMessage+DataRow.swift
Labels: bug, enhancement

#97 1.0.0 gm
  .github/CODE_OF_CONDUCT.md
  README.md
  Sources/PostgresNIO/Connection/PostgresConnection+Database.swift
  Sources/PostgresNIO/Connection/PostgresDatabase+Close.swift
  Sources/PostgresNIO/Connection/PostgresDatabase+PreparedQuery.swift
  Sources/PostgresNIO/Data/PostgresData+Array.swift
  Sources/PostgresNIO/Message/PostgresMessage+Close.swift
  Sources/PostgresNIO/Message/PostgresMessage+DataRow.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
Labels: enhancement

#103 Too many binds error
  Sources/PostgresNIO/PostgresDatabase+Query.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
Labels: bug, semver-patch

#105 RawRepresentable + PostgresData conformance
  Sources/PostgresNIO/Data/PostgresData+RawRepresentable.swift
Labels: enhancement, semver-minor
