Repository vapor/postgres-nio, pull requests merged in 2020-02, with the labels that each got.

#72 char(n) (BPCHAR) length fix
  Sources/PostgresNIO/Data/PostgresData+Int.swift
  Sources/PostgresNIO/Data/PostgresData+String.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
Labels: bug, semver-patch

#82 Handle NAME Type in PropertyData.string Property
  .github/workflows/test.yml
  Sources/PostgresNIO/Data/PostgresData+String.swift
Labels: bug, semver-patch

#83 Support Swift.Set
  Sources/PostgresNIO/Data/PostgresData+Set.swift
  Tests/PostgresNIOTests/PostgresNIOTests.swift
Labels: enhancement, semver-minor

#85 Release Candidate 1
  .github/workflows/test.yml
  Package.swift
  README.md
  Sources/CMD5/CMD5.c
  Sources/CMD5/include/CMD5.h
  Sources/PostgresNIO/Connection/PostgresConnection+Authenticate.swift
Labels: enhancement
