Repository vapor/postgres-nio, pull requests merged in 2021-11, with the labels that each got.

#191 Rewire CI a bit
  .github/workflows/test.yml
Labels: enhancement, no-release-needed

#192 Prefix default usernames and password for test with test_ instead of vapor_
  .github/workflows/test.yml
  README.md
  Tests/IntegrationTests/PSQLIntegrationTests.swift
  Tests/IntegrationTests/Utilities.swift
  docker-compose.yml
Labels: no-release-needed

#193 Update docker-compose.yml just in case anyone's using it
  docker-compose.yml
Labels: no-release-needed

#196 Move pre 1.5.0 unit tests into the unit test target
  Tests/IntegrationTests/PostgresNIOTests.swift
  Tests/PostgresNIOTests/Data/PostgresData+JSONTests.swift
  Tests/PostgresNIOTests/Message/PostgresMessageDecoderTests.swift
  Tests/PostgresNIOTests/Utilities/PostgresJSONCodingTests.swift
Labels: enhancement, no-release-needed

#197 Rejigger test matrix again
  .github/workflows/test.yml
Labels: enhancement, no-release-needed

#198 DataRow without allocation; DataRow as Collection; RowDescription top level
  Sources/PostgresNIO/Connection/PostgresConnection+Database.swift
  Sources/PostgresNIO/New/Connection State Machine/ConnectionStateMachine.swift
  Sources/PostgresNIO/New/Connection State Machine/ExtendedQueryStateMachine.swift
  Sources/PostgresNIO/New/Connection State Machine/PrepareStatementStateMachine.swift
  Sources/PostgresNIO/New/Connection State Machine/RowStreamStateMachine.swift
  Sources/PostgresNIO/New/Messages/DataRow.swift
  Sources/PostgresNIO/New/Messages/RowDescription.swift
  Sources/PostgresNIO/New/PSQLChannelHandler.swift
  Sources/PostgresNIO/New/PSQLConnection.swift
  Sources/PostgresNIO/New/PSQLPreparedStatement.swift
  Sources/PostgresNIO/New/PSQLRow.swift
  Sources/PostgresNIO/New/PSQLRowStream.swift
  Sources/PostgresNIO/New/PSQLTask.swift
  Tests/PostgresNIOTests/New/Connection State Machine/ExtendedQueryStateMachineTests.swift
  Tests/PostgresNIOTests/New/Connection State Machine/PrepareStatementStateMachineTests.swift
  Tests/PostgresNIOTests/New/Extensions/PSQLBackendMessage+Equatable.swift
  Tests/PostgresNIOTests/New/Extensions/PSQLBackendMessageEncoder.swift
  Tests/PostgresNIOTests/New/Messages/DataRowTests.swift
  Tests/PostgresNIOTests/New/Messages/RowDescriptionTests.swift
Labels: enhancement, semver-patch

#202 Experimental switch to our codecov-action wrapper
  .github/workflows/main-codecov.yml
  .github/workflows/test.yml
Labels: enhancement, no-release-needed

#194 Add proper support for `Decimal`
  Sources/PostgresNIO/Data/PostgresData+Decimal.swift
  Sources/PostgresNIO/New/Data/Decimal+PSQLCodable.swift
  Tests/IntegrationTests/PSQLIntegrationTests.swift
  Tests/IntegrationTests/PostgresNIOTests.swift
  Tests/PostgresNIOTests/New/Data/Decimal+PSQLCodableTests.swift
Labels: enhancement, semver-minor

#203 Faster decoding, thanks to fewer bound checks.
  Package.swift
  Sources/PostgresNIO/Message/PostgresMessage+Authentication.swift
  Sources/PostgresNIO/Message/PostgresMessage+Bind.swift
  Sources/PostgresNIO/Message/PostgresMessage+Close.swift
  Sources/PostgresNIO/Message/PostgresMessage+CommandComplete.swift
  Sources/PostgresNIO/Message/PostgresMessage+Describe.swift
  Sources/PostgresNIO/Message/PostgresMessage+Error.swift
  Sources/PostgresNIO/Message/PostgresMessage+Execute.swift
  Sources/PostgresNIO/Message/PostgresMessage+NotificationResponse.swift
  Sources/PostgresNIO/Message/PostgresMessage+ParameterStatus.swift
  Sources/PostgresNIO/Message/PostgresMessage+RowDescription.swift
  Sources/PostgresNIO/Message/PostgresMessage+SASLResponse.swift
  Sources/PostgresNIO/New/Data/Array+PSQLCodable.swift
  Sources/PostgresNIO/New/Extensions/ByteBuffer+PSQL.swift
  Sources/PostgresNIO/New/Messages/Authentication.swift
  Sources/PostgresNIO/New/Messages/BackendKeyData.swift
  Sources/PostgresNIO/New/Messages/Bind.swift
  Sources/PostgresNIO/New/Messages/Cancel.swift
  Sources/PostgresNIO/New/Messages/Close.swift
  Sources/PostgresNIO/New/Messages/DataRow.swift
  Sources/PostgresNIO/New/Messages/Describe.swift
  Sources/PostgresNIO/New/Messages/ErrorResponse.swift
  Sources/PostgresNIO/New/Messages/Execute.swift
  Sources/PostgresNIO/New/Messages/NotificationResponse.swift
  Sources/PostgresNIO/New/Messages/ParameterDescription.swift
  Sources/PostgresNIO/New/Messages/ParameterStatus.swift
  Sources/PostgresNIO/New/Messages/Parse.swift
  Sources/PostgresNIO/New/Messages/Password.swift
  Sources/PostgresNIO/New/Messages/ReadyForQuery.swift
  Sources/PostgresNIO/New/Messages/RowDescription.swift
  Sources/PostgresNIO/New/Messages/SASLInitialResponse.swift
  Sources/PostgresNIO/New/Messages/Startup.swift
  Sources/PostgresNIO/New/PSQLBackendMessage.swift
  Sources/PostgresNIO/New/PSQLBackendMessageDecoder.swift
  Tests/PostgresNIOTests/New/Extensions/PSQLBackendMessageEncoder.swift
  Tests/PostgresNIOTests/New/Extensions/PSQLFrontendMessageDecoder.swift
  Tests/PostgresNIOTests/New/Messages/BindTests.swift
  Tests/PostgresNIOTests/New/Messages/CloseTests.swift
  Tests/PostgresNIOTests/New/Messages/DescribeTests.swift
  Tests/PostgresNIOTests/New/Messages/ErrorResponseTests.swift
  Tests/PostgresNIOTests/New/Messages/ExecuteTests.swift
  Tests/PostgresNIOTests/New/Messages/NotificationResponseTests.swift
  Tests/PostgresNIOTests/New/Messages/ParameterStatusTests.swift
  Tests/PostgresNIOTests/New/Messages/ParseTests.swift
  Tests/PostgresNIOTests/New/Messages/PasswordTests.swift
  Tests/PostgresNIOTests/New/Messages/RowDescriptionTests.swift
  Tests/PostgresNIOTests/New/Messages/SASLInitialResponseTests.swift
  Tests/PostgresNIOTests/New/Messages/StartupTests.swift
  Tests/PostgresNIOTests/New/PSQLBackendMessageTests.swift
Labels: enhancement, semver-patch

#201 Refactor PSQLRowStream to make async/await easier
  Sources/PostgresNIO/New/PSQLRow.swift
  Sources/PostgresNIO/New/PSQLRowStream.swift
  Tests/PostgresNIOTests/New/PSQLRowStreamTests.swift
Labels: enhancement, semver-patch
