Repository vapor/postgres-nio, pull requests merged in 2023-10, with the labels that each got.

#414 Update minimum Swift requirement to 5.7
  .github/workflows/test.yml
  Package.swift
  README.md
  Sources/PostgresNIO/Docs.docc/images/vapor-postgres-logo.svg
  Sources/PostgresNIO/Docs.docc/theme-settings.json
  docker-compose.yml
Labels: semver-minor

#412 Add target `ConnectionPoolModule`
  Package.swift
  Sources/ConnectionPoolModule/gitkeep.swift
  Tests/ConnectionPoolModuleTests/gitkeep.swift
Labels: semver-patch

#416 Vendor SwiftNIO NIOLock into the new `ConnectionPoolModule` target
  NOTICE.txt
  Sources/ConnectionPoolModule/NIOLock.swift
  Sources/ConnectionPoolModule/gitkeep.swift
Labels: semver-patch

#417 Add `PooledConnection` protocol
  Sources/ConnectionPoolModule/ConnectionPool.swift
Labels: semver-patch

#418 Add `ConnectionIDGenerator` and `NoOpKeepAliveBehavior`
  Sources/ConnectionPoolModule/ConnectionIDGenerator.swift
  Sources/ConnectionPoolModule/NoKeepAliveBehavior.swift
  Tests/ConnectionPoolModuleTests/ConnectionIDGeneratorTests.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockConnection.swift
  Tests/ConnectionPoolModuleTests/NoKeepAliveBehaviorTests.swift
  Tests/ConnectionPoolModuleTests/gitkeep.swift
Labels: semver-patch

#420 Add `OneElementFastSequence` to be used in `ConnectionPool`
  Sources/ConnectionPoolModule/OneElementFastSequence.swift
  Tests/ConnectionPoolModuleTests/OneElementFastSequence.swift
Labels: semver-patch

#419 Add `Max2Sequence` to be used in `ConnectionPool`
  Sources/ConnectionPoolModule/Max2Sequence.swift
  Tests/ConnectionPoolModuleTests/Max2SequenceTests.swift
Labels: semver-patch

#421 Add `ConnectionRequestProtocol`, `ConnectionPoolError` and `ConnectionPoolConfiguration`
  Sources/ConnectionPoolModule/ConnectionPool.swift
  Sources/ConnectionPoolModule/ConnectionPoolError.swift
  Sources/ConnectionPoolModule/ConnectionRequest.swift
Labels: semver-patch

#422 Add `ConnectionPoolObservabilityDelegate`
  Sources/ConnectionPoolModule/ConnectionPoolObservabilityDelegate.swift
Labels: semver-patch

#423 Fix `PostgresDecodable` inference for `RawRepresentable` enums
  Sources/PostgresNIO/New/Data/RawRepresentable+PostgresCodable.swift
  Tests/IntegrationTests/PSQLIntegrationTests.swift
Labels: semver-minor

#425 Add `PoolStateMachine.ConnectionState`
  Sources/ConnectionPoolModule/Max2Sequence.swift
  Sources/ConnectionPoolModule/PoolStateMachine+ConnectionState.swift
  Sources/ConnectionPoolModule/PoolStateMachine.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockTimerCancellationToken.swift
  Tests/ConnectionPoolModuleTests/PoolStateMachine+ConnectionStateTests.swift
Labels: semver-patch

#426 Add `PoolStateMachine.ConnectionGroup` (#425)
  Sources/ConnectionPoolModule/Max2Sequence.swift
  Sources/ConnectionPoolModule/PoolStateMachine+ConnectionGroup.swift
  Sources/ConnectionPoolModule/PoolStateMachine+ConnectionState.swift
  Sources/ConnectionPoolModule/PoolStateMachine.swift
  Tests/ConnectionPoolModuleTests/PoolStateMachine+ConnectionGroupTests.swift
  Tests/ConnectionPoolModuleTests/PoolStateMachine+ConnectionStateTests.swift
Labels: semver-patch

#427 Add `PoolStateMachine`
  Sources/ConnectionPoolModule/PoolStateMachine+ConnectionGroup.swift
  Sources/ConnectionPoolModule/PoolStateMachine+RequestQueue.swift
  Sources/ConnectionPoolModule/PoolStateMachine.swift
  Sources/ConnectionPoolModule/TinyFastSequence.swift
  Tests/ConnectionPoolModuleTests/PoolStateMachine+ConnectionGroupTests.swift
  Tests/ConnectionPoolModuleTests/PoolStateMachineTests.swift
  Tests/ConnectionPoolModuleTests/TinyFastSequence.swift
Labels: semver-patch

#428 Land ConnectionPool
  Sources/ConnectionPoolModule/ConnectionPool.swift
  Sources/ConnectionPoolModule/ConnectionRequest.swift
  Sources/ConnectionPoolModule/NIOLockedValueBox.swift
  Sources/ConnectionPoolModule/PoolStateMachine+ConnectionGroup.swift
  Sources/ConnectionPoolModule/PoolStateMachine.swift
  Tests/ConnectionPoolModuleTests/ConnectionPoolTests.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockClock.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockConnection.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockPingPongBehaviour.swift
  Tests/ConnectionPoolModuleTests/PoolStateMachine+ConnectionGroupTests.swift
  Tests/ConnectionPoolModuleTests/PoolStateMachineTests.swift
  Tests/ConnectionPoolModuleTests/TinyFastSequenceTests.swift
Labels: semver-patch

#429 Ensure pool runs until all connections are closed
  Sources/ConnectionPoolModule/ConnectionPool.swift
  Sources/ConnectionPoolModule/PoolStateMachine+RequestQueue.swift
  Sources/ConnectionPoolModule/PoolStateMachine.swift
  Tests/ConnectionPoolModuleTests/ConnectionPoolTests.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockConnection.swift
Labels: semver-patch

#430 Land PostgresClient that is backed by a ConnectionPool as SPI
  Sources/ConnectionPoolModule/PoolStateMachine+ConnectionGroup.swift
  Sources/ConnectionPoolModule/PoolStateMachine.swift
  Sources/PostgresNIO/Connection/PostgresConnection.swift
  Sources/PostgresNIO/New/Connection State Machine/ConnectionStateMachine.swift
  Sources/PostgresNIO/New/PSQLError.swift
  Sources/PostgresNIO/Pool/ConnectionFactory.swift
  Sources/PostgresNIO/Pool/PostgresClient.swift
  Sources/PostgresNIO/Pool/PostgresClientMetrics.swift
  Sources/PostgresNIO/Postgres+PSQLCompat.swift
  Tests/ConnectionPoolModuleTests/PoolStateMachine+ConnectionGroupTests.swift
  Tests/IntegrationTests/PostgresClientTests.swift
Labels: semver-patch, ConnectionPool
