Repository vapor/postgres-nio, pull requests merged in 2023-11, with the labels that each got.

#434 Update README.md
  README.md
Labels: semver-noop

#438 Fixes Crash in ConnectionPoolStateMachine
  Sources/ConnectionPoolModule/PoolStateMachine+ConnectionGroup.swift
  Sources/ConnectionPoolModule/PoolStateMachine+ConnectionState.swift
  Tests/ConnectionPoolModuleTests/ConnectionPoolTests.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockClock.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockConnection.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockConnectionFactory.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockPingPongBehaviour.swift
  Tests/ConnectionPoolModuleTests/PoolStateMachine+ConnectionStateTests.swift
Labels: semver-patch

#439 Test cancel connection request
  Tests/ConnectionPoolModuleTests/ConnectionPoolTests.swift
  Tests/ConnectionPoolModuleTests/Utils/Waiter.swift
Labels: semver-noop

#440 Add tests to lease multiple connections at once
  Tests/ConnectionPoolModuleTests/ConnectionPoolTests.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockConnectionFactory.swift
  Tests/ConnectionPoolModuleTests/Utils/Future.swift
Labels: semver-noop

#441 Add Test: Lease connection after shutdown has started fails
  Tests/ConnectionPoolModuleTests/ConnectionPoolTests.swift
  Tests/ConnectionPoolModuleTests/Mocks/MockConnection.swift
Labels: semver-noop, ConnectionPool

#442 Add support for multiple streams
  Sources/ConnectionPoolModule/ConnectionPool.swift
  Sources/ConnectionPoolModule/PoolStateMachine+ConnectionGroup.swift
  Sources/ConnectionPoolModule/PoolStateMachine+ConnectionState.swift
  Sources/ConnectionPoolModule/PoolStateMachine.swift
  Tests/ConnectionPoolModuleTests/ConnectionPoolTests.swift
Labels: semver-minor, ConnectionPool
