Repository vapor/postgres-nio, pull requests merged in 2023-08, with the labels that each got.

#379 Crash fix: Multiple bad messages could trigger reentrancy issue
  Sources/PostgresNIO/New/Connection State Machine/ConnectionStateMachine.swift
  Sources/PostgresNIO/New/PostgresChannelHandler.swift
  Tests/PostgresNIOTests/New/PostgresChannelHandlerTests.swift
Labels: semver-patch

#381 PostgresFrontendMessage: refactor encoding
  Sources/PostgresNIO/New/BufferedMessageEncoder.swift
  Sources/PostgresNIO/New/Messages/Bind.swift
  Sources/PostgresNIO/New/Messages/Cancel.swift
  Sources/PostgresNIO/New/Messages/Close.swift
  Sources/PostgresNIO/New/Messages/Describe.swift
  Sources/PostgresNIO/New/Messages/Execute.swift
  Sources/PostgresNIO/New/Messages/Parse.swift
  Sources/PostgresNIO/New/Messages/Password.swift
  Sources/PostgresNIO/New/Messages/SASLInitialResponse.swift
  Sources/PostgresNIO/New/Messages/SASLResponse.swift
  Sources/PostgresNIO/New/Messages/SSLRequest.swift
  Sources/PostgresNIO/New/Messages/Startup.swift
  Sources/PostgresNIO/New/PSQLFrontendMessageEncoder.swift
  Sources/PostgresNIO/New/PostgresChannelHandler.swift
  Sources/PostgresNIO/New/PostgresFrontendMessage.swift
  Sources/PostgresNIO/New/PostgresFrontendMessageEncoder.swift
  Tests/PostgresNIOTests/New/Extensions/PSQLFrontendMessageDecoder.swift
  Tests/PostgresNIOTests/New/Messages/BindTests.swift
  Tests/PostgresNIOTests/New/Messages/CancelTests.swift
  Tests/PostgresNIOTests/New/Messages/CloseTests.swift
  Tests/PostgresNIOTests/New/Messages/DescribeTests.swift
  Tests/PostgresNIOTests/New/Messages/ExecuteTests.swift
  Tests/PostgresNIOTests/New/Messages/ParseTests.swift
  Tests/PostgresNIOTests/New/Messages/PasswordTests.swift
  Tests/PostgresNIOTests/New/Messages/SASLInitialResponseTests.swift
  Tests/PostgresNIOTests/New/Messages/SASLResponseTests.swift
  Tests/PostgresNIOTests/New/Messages/SSLRequestTests.swift
  Tests/PostgresNIOTests/New/Messages/StartupTests.swift
  Tests/PostgresNIOTests/New/PSQLFrontendMessageTests.swift
  Tests/PostgresNIOTests/New/PostgresChannelHandlerTests.swift
Labels: semver-patch

#264 Start work on async listen
  Sources/PostgresNIO/Connection/PostgresConnection.swift
  Sources/PostgresNIO/New/Connection State Machine/ConnectionStateMachine.swift
  Sources/PostgresNIO/New/Connection State Machine/ListenStateMachine.swift
  Sources/PostgresNIO/New/NotificationListener.swift
  Sources/PostgresNIO/New/PSQLError.swift
  Sources/PostgresNIO/New/PSQLTask.swift
  Sources/PostgresNIO/New/PostgresChannelHandler.swift
  Sources/PostgresNIO/New/PostgresFrontendMessage.swift
  Sources/PostgresNIO/New/PostgresNotificationSequence.swift
  Sources/PostgresNIO/Postgres+PSQLCompat.swift
  Tests/IntegrationTests/AsyncTests.swift
  Tests/PostgresNIOTests/New/Extensions/PSQLFrontendMessageDecoder.swift
  Tests/PostgresNIOTests/New/PSQLConnectionTests.swift
  Tests/PostgresNIOTests/New/PostgresChannelHandlerTests.swift
  Tests/PostgresNIOTests/New/PostgresConnectionTests.swift
Labels: semver-minor

#386 PostgresBackendMessage.ID should be backed by UInt8 directly
  Sources/PostgresNIO/New/PostgresBackendMessage.swift
  Sources/PostgresNIO/New/PostgresBackendMessageDecoder.swift
Labels: semver-patch

#389 Use EventLoop provided by SwiftNIO's MultiThreadedEventLoopGroup.singleton
  Package.swift
  README.md
  Sources/PostgresNIO/Connection/PostgresConnection.swift
Labels: semver-minor

#383 `close()` closes immediately; Add new `closeGracefully()`
  Sources/PostgresNIO/Connection/PostgresConnection.swift
  Sources/PostgresNIO/New/Connection State Machine/ConnectionStateMachine.swift
  Sources/PostgresNIO/New/Connection State Machine/ListenStateMachine.swift
  Sources/PostgresNIO/New/PSQLError.swift
  Sources/PostgresNIO/New/PSQLEventsHandler.swift
  Sources/PostgresNIO/New/PostgresChannelHandler.swift
  Sources/PostgresNIO/Postgres+PSQLCompat.swift
  Tests/PostgresNIOTests/New/Connection State Machine/ConnectionStateMachineTests.swift
  Tests/PostgresNIOTests/New/PSQLRowStreamTests.swift
  Tests/PostgresNIOTests/New/PostgresChannelHandlerTests.swift
  Tests/PostgresNIOTests/New/PostgresConnectionTests.swift
  Tests/PostgresNIOTests/New/PostgresRowSequenceTests.swift
Labels: semver-minor

#390 async/await prepared statement API
  Sources/PostgresNIO/Connection/PostgresConnection.swift
  Sources/PostgresNIO/New/Connection State Machine/PreparedStatementStateMachine.swift
  Sources/PostgresNIO/New/PSQLTask.swift
  Sources/PostgresNIO/New/PostgresChannelHandler.swift
  Sources/PostgresNIO/New/PostgresQuery.swift
  Sources/PostgresNIO/New/PreparedStatement.swift
  Tests/IntegrationTests/AsyncTests.swift
  Tests/PostgresNIOTests/New/Connection State Machine/PreparedStatementStateMachineTests.swift
  Tests/PostgresNIOTests/New/Extensions/PSQLFrontendMessageDecoder.swift
  Tests/PostgresNIOTests/New/PostgresConnectionTests.swift
Labels: semver-minor

#395 Cleanup encoding Startup message
  Sources/PostgresNIO/New/Messages/Startup.swift
  Sources/PostgresNIO/New/PostgresChannelHandler.swift
  Sources/PostgresNIO/New/PostgresFrontendMessage.swift
  Sources/PostgresNIO/New/PostgresFrontendMessageEncoder.swift
  Tests/PostgresNIOTests/New/Extensions/PSQLBackendMessageEncoder.swift
  Tests/PostgresNIOTests/New/Messages/StartupTests.swift
  Tests/PostgresNIOTests/New/PostgresChannelHandlerTests.swift
Labels: semver-patch

#398 Fix a few inaccurate or confusing precondition failure messages
  Sources/PostgresNIO/New/Connection State Machine/ConnectionStateMachine.swift
Labels: enhancement, semver-noop

#399 Move PostgresFrontendMessage to tests
  Sources/PostgresNIO/New/Extensions/ByteBuffer+PSQL.swift
  Sources/PostgresNIO/New/PostgresFrontendMessageEncoder.swift
  Tests/PostgresNIOTests/New/Extensions/ByteBuffer+Utils.swift
  Tests/PostgresNIOTests/New/Extensions/PostgresFrontendMessage.swift
Labels: semver-patch

#400 Remove PSQLError.Code.clientClosesConnection
  Sources/PostgresNIO/New/Connection State Machine/ConnectionStateMachine.swift
  Sources/PostgresNIO/New/PSQLError.swift
  Sources/PostgresNIO/New/PostgresChannelHandler.swift
  Sources/PostgresNIO/Postgres+PSQLCompat.swift
  Tests/PostgresNIOTests/New/PostgresChannelHandlerTests.swift
Labels: semver-minor

#341 Use variadic generics in Swift 5.9
  Sources/PostgresNIO/New/PostgresRow-multi-decode.swift
  Sources/PostgresNIO/New/PostgresRowSequence-multi-decode.swift
  Sources/PostgresNIO/New/VariadicGenerics.swift
  Tests/IntegrationTests/AsyncTests.swift
  Tests/IntegrationTests/PostgresNIOTests.swift
  Tests/PostgresNIOTests/New/PostgresRowSequenceTests.swift
Labels: semver-patch

#365 Add PostgresDynamicTypeThrowingEncodable and PostgresDynamicTypeEncodable
  Sources/PostgresNIO/New/Data/Array+PostgresCodable.swift
  Sources/PostgresNIO/New/Data/Range+PostgresCodable.swift
  Sources/PostgresNIO/New/PostgresCodable.swift
  Sources/PostgresNIO/New/PostgresQuery.swift
  Tests/PostgresNIOTests/New/PostgresQueryTests.swift
Labels: semver-minor

#404 Improve the logo image used by the DocC catalog
  Sources/PostgresNIO/Docs.docc/images/vapor-postgres-logo.svg
  Sources/PostgresNIO/Docs.docc/theme-settings.json
Labels: semver-noop
