Repository vapor/postgres-nio, pull requests merged in 2024-12, with the labels that each got.

#527 Correctly place the SSL channel handler in front of the PostgresChannelHandler
  Sources/PostgresNIO/Connection/PostgresConnection.swift
  Sources/PostgresNIO/New/PostgresChannelHandler.swift
  Tests/PostgresNIOTests/New/PostgresChannelHandlerTests.swift
Labels: semver-patch

#526 Allow TLS enabled connections when providing an established channel
  Sources/PostgresNIO/Connection/PostgresConnection+Configuration.swift
Labels: semver-minor

#529 Update DocC settings to latest version of Vapor theme
  Sources/PostgresNIO/Docs.docc/theme-settings.json
Labels: semver-noop

#530 Fix malformed JSON in theme settings
  Sources/PostgresNIO/Docs.docc/theme-settings.json
Labels: semver-noop
